cloud-gov/logsearch-for-cloudfoundry

ci/pipeline.yml
I noticed that we're not triggering updates on source change after I merged in a patch from @sharms and we didn't get a new release. Maybe we have a reason not to trigger, but I don't know what it is, so here's this PR.
=> Trigger on source change.

jobs/push-kibana/spec, jobs/push-kibana/templates/config/manifest.yml
To handle https://github.com/18F/cg-atlas/issues/133, we're going to use a custom cf domain (logs.cloud.gov) with `no-hostname: true` instead of using the cloud.gov domain with the logs hostname. This patch lets us set `no-hostname` in the manifest from the properties.
@LinuxBozo
=> Add no-hostname option to kibana application.

config/blobs.yml, jobs/cf-kibana/spec, jobs/cf-kibana/templates/kibana.yml.erb, jobs/elasticsearch-config-lfc/templates/index-mappings-app.json.erb, jobs/elasticsearch-config-lfc/templates/index-mappings-platform.json.erb, jobs/elasticsearch-config-lfc/templates/index-mappings.json.erb, jobs/upload-kibana-objects/spec, jobs/upload-kibana-objects/templates/bin/run, jobs/upload-kibana-objects/templates/kibana-objects/config/6.3.2.json.erb, packages/cf-kibana/packaging, packages/cf-kibana/spec, src/kibana-cf_authentication/package.json
change types and mappings and kibana config to work with ES6, update to ES6, etc.
This goes with https://github.com/18F/logsearch-boshrelease/pull/6
Make sure that https://github.com/18F/cg-deploy-logsearch/pull/141 is merged first, so that the proper logsearch-platform default index pattern is selected.
=> Upgrade to es6

packages/logsearch-config-logstash-filters/spec
Signed-off-by: Mike Lloyd <mike.lloyd@gsa.gov>
=> logstash contained a dependency on the old version of ruby.

src/logsearch-config/spec/logstash-filters/snippets/app_logmessage_rtr_spec.rb, src/logsearch-config/src/logstash-filters/snippets/app-logmessage-rtr.conf
This should fix the issue we're having where router log formats changed with cf 12.17
> These fields were introduced in routing-release 0.196.0 https://github.com/cloudfoundry/routing-release/releases/tag/0.196.0 which forms part of cf-deployment v12.17.0 https://github.com/cloudfoundry/cf-deployment/releases/tag/v12.17.0
None
=> Add a logmessage_rtr config for new gorouter_time and app_time fields

config/blobs.yml, jobs/upload-kibana-objects/spec, jobs/upload-kibana-objects/templates/bin/import-objects, packages/upload-kibana-objects-python3/packaging, packages/upload-kibana-objects-python3/spec
- Add a package that bundles the python packages needed for upload-kibana-objects
- use that package
This should fix the `upload-kibana-objects` job in the tenant logsearch instances
Since we are vendoring python pakages now, we'll need to keep an eye on their CVEs
=> Create and use a package for the python deps of upload-kibana-objects

packages/upload-kibana-objects-python3/packaging
- Set the python path explicitly, rather than basing it on `BOSH_INSTALL_TARGET`
None
=> set path explicitly

jobs/elasticsearch-config-lfc/templates/index-mappings.json.erb
revert the schema of the norms key to match v6.
none
=> revert norms schema to v6

config/blobs.yml, config/final.yml
- Uses the cloud.gov blobstore instead of the default.
- Updates blobs to v211.1.0 in our blobstore
none
=> Use cg blobstore and update blobs

jobs/elasticsearch-config-lfc/templates/index-mappings-app.json.erb, jobs/elasticsearch-config-lfc/templates/index-mappings-platform.json.erb, jobs/elasticsearch-config-lfc/templates/index-mappings.json.erb
This changeset fixes an issue with JSON formatting and cleans up the templates to make them a bit more readable.
h/t @soutenniza for the help in tracking this down!
- Fix extraneous `,`
- Improve readability
- None:  JSON template fixes
=> Fix JSON formatting

src/kibana-cf_authentication/server/index.js, src/kibana-cf_authentication/server/routes.js
This changeset adds support for filering auto-suggest values based on the access and permissions granted to the authenticated user.
- Adds a new method to handle filtering suggestions
- Formatting updates
- Prevents users from seeing suggestions for apps, orgs, spaces, etc., that they do not have access to when adding filters
=> Add filtering for auto-suggest values

src/kibana-cf_authentication/server/index.js
This changeset fixes a URL path that was missing a character.
- Adds a missing `/`
- None; URL path change
=> Fix URL path check

src/kibana-cf_authentication/server/index.js, src/kibana-cf_authentication/server/routes.js
This changeset fixes the request handling for filtered suggestions so that the index name flows through to the handler.
- Adds regex matching to retrieve the index name being searched
- None; URL path handling fix
=> Fix the request handling for filtered suggestions

src/kibana-cf_authentication/server/routes.js
This changeset swaps the suggestion endpoint to use the `filterQuery` method instead of `filterInternalQuery`.
- Swap method calls
- None; switching function calls between two methods that are both already used.
=> Swap filter function for payload modification

src/kibana-cf_authentication/server/helpers.js, src/kibana-cf_authentication/server/routes.js
This changeset creates a new method to inject the org and space filtering into the payload used by the suggestion endpoint for the edit filter functionality in Kibana.
- Adds a new method to modify the suggestion endpoint payload
- Changes the suggestion route handler to use the new method
- None; adjusting how the payload is constructed for filtering and modifying the route handler for suggestions
=> Adjust suggestion payload for edit filters

src/kibana-cf_authentication/server/routes.js
This changeset modifies the suggestion route handler to behave more like the other _msearch handler; trying to see if this gets Kibana to pick up on the filtering changes we are trying to enforce.
- Swap handler method to match the `_msearch` method for suggestions
- None; modifying the suggestions route handler to behave like another.
=> Tweak suggestion route handler

src/kibana-cf_authentication/server/index.js, src/kibana-cf_authentication/server/routes.js
- fix payload manipulation for suggestion endpoint filtering. The original function was based on the _msearch filtering, which has a weird, non-JSON request body like:
```
logs-app-2020.12.28
{"json":{"for":["a", "query"]}}
logs-app-2020.12.27
{"json":{"for":["another", "query"]}}
```
This function now more closely matches the other filtered endpoint functions
- run suggestions only against specific indices: this rolls back a simplification that Van and Carlo put in when they were troubleshooting. It means that when a request for a filtered suggestion is sent in, we send the modified query to the index it was originally sent to, rather than assuming they can all go to `logs-app*`. this is better for both performance and generalization
-
Properly filters users' queries so we can safely …
=> Correct return type

.gitignore, packages/kibana-auth-plugin/spec, src/kibana-cf_authentication/README.md, src/kibana-cf_authentication/jest.config.js, src/kibana-cf_authentication/package.json, src/kibana-cf_authentication/server/ensureKeys.test.js, src/kibana-cf_authentication/server/helpers.js
- Add the `script` tag with `test` command to `package.json` to run tests in a future CI task without needing to install dev dependencies
- CI task will be able to run tests with `$ npm test` command
None
=> Add test script to run tests in ci task later

src/kibana-cf_authentication/server/ensureKeys.test.js
Reverts cloud-gov/logsearch-for-cloudfoundry#71
All done testing
None
=> Revert "add bad test to test ci"

src/kibana-cf_authentication/server/routes.js
- return the response rather than the text; I don't know why the rest of the routes aren't doing this, but we need
to return the response object rather than the response body
None
=> return the response rather than the text

src/logsearch-config/src/logstash-filters/snippets/app-logmessage-app.conf, src/logsearch-config/src/logstash-filters/snippets/app-logmessage-rtr.conf, src/logsearch-config/src/logstash-filters/snippets/app.conf, src/logsearch-config/src/logstash-filters/snippets/platform-cloud_controller_ng.conf, src/logsearch-config/src/logstash-filters/snippets/platform-gorouter.conf, src/logsearch-config/src/logstash-filters/snippets/platform-haproxy.conf, src/logsearch-config/src/logstash-filters/snippets/platform-uaa.conf, src/logsearch-config/src/logstash-filters/snippets/platform-vcap.conf, src/logsearch-config/src/logstash-filters/snippets/platform.conf
- add ids to grok and json filters. When we don't set IDs, logsearch sets them dynamically, but there's no way I've found to trace them back. Adding ids to these filters should make it easier to debug performance issues and track filter usage
I also tidied up a bunch of whitespace in the process, so I'd recommend viewing this PR with whitespace changes ignored.
None
=> add ids to grok and json filters

src/kibana-cf_authentication/server/helpers.js, src/kibana-cf_authentication/server/index.js, src/kibana-cf_authentication/server/routes.js
This changeset adds filters for the org and space of a user, just like we had done for the filter suggestions and main search results previously.  This prevents CSVs from being generated that include all logs, instead of just the logs specific to a customer.
- Add specific CSV endpoint to the `allowlist`
- Add a filter method for the CSV report endpoint
- Add a route handler for the CSV report endpoint
- Locks down CSV generation to only include log output that is visible to a given customer
=> Lock down CSV generation endpoint

src/kibana-cf_authentication/server/helpers.js
We will need to adjust the denylist after to account for the PDF report endpoint.
- Updates the `denylist` to remove the reporting endpoint for now
- The PDF endpoint (and any other reporting endpoints) will still need to be accounted for once we finish our CSV testing
=> Allow the CSV endpoint to work

src/kibana-cf_authentication/package.json, src/kibana-cf_authentication/server/helpers.js
This changeset is an attempt to fix the CSV report generation in Kibana.  It adds support for Rison string processing, which is required to process the payload Kibana creates for generating a CSV (see https://www.elastic.co/guide/en/kibana/7.x/reporting-integration.html for details).
- Adds the `rison-node` package for Rison string processing
- Updates the `jobsParams` payload processing to account for the Rison string
- Attempts to fix the log leakage we experienced with the CSV report in Kibana
=> Attempt to fix CSV Report Generation

src/kibana-cf_authentication/server/helpers.js, src/kibana-cf_authentication/server/routes.js
Previously, we thought that the payload itself was the value of the `jobParam` query parameter, but it appears that the payload includes this as well.  We need to decode the Rison value before modifying the underlying `bool` filter and then encode it again when injecting them into the request payload on the server itself.  This changeset attempts to fix the order of things to make this work.
- Shifts the Rison encoding/decoding to the URL handler itself
- Hopefully adjusts the request payload properly
- None; still attempting to make the CSV report work with the correct filters
=> Fix CSV URL and request payload handling

src/kibana-cf_authentication/server/helpers.js, src/kibana-cf_authentication/server/routes.js
This changeset introduces a couple of minor fixes to attempt making the CSV report generation work.
- Fixes a variable reference
- Makes sure the main `jobParams` request property is reset with the updated values
- Sill trying to ensure the CSV report generation accounts for user authorization (proper space and org access)
=> Minor fixes to try CSV report generation again

src/kibana-cf_authentication/server/helpers.js
- Explicitly pass `console` into the method to make sure it is within scope
- Logging statements need to be removed when debugging is done
=> Make sure console is available in the filterCSVReportingQuery method

src/kibana-cf_authentication/server/helpers.js
- Removes the logging statements
- None; the implementation now appears to be working correctly to restrict CSV output to only orgs and spaces a user has access to
=> Remove logging statements

jobs/elasticsearch-config-lfc/templates/component-index-mappings-app.json.erb
Currently, [when Logstash receives an input log that is JSON, it parses the JSON properties into a field called `app`](https://github.com/cloud-gov/logsearch-for-cloudfoundry/blob/develop/src/logsearch-config/src/logstash-filters/snippets/app-logmessage-app.conf#L24).
While this behavior is nice in that it allows logs to be searched by the custom properties from the JSON log (based on the detected field type for each JSON property), it can lead to a "mapping explosion" where fields dynamically generated from JSON logs hit the available field limit as discussed here: https://discuss.elastic.co/t/approaches-to-deal-with-limit-of-total-fields-1000-in-index-has-been-exceeded/241039. And once the total field limit for an index has been hit, no other logs with custom fields can be indexed, …
=> add mapping for "app" field as flattened type 

jobs/elasticsearch-config-lfc/templates/component-index-mappings-app.json.erb
Follow-up to #115 
- remove mapping of "app" field as "flattened" type. It turns out the `flattened` field type is not supported by default in Elasticsearch 7.9, but is only offered as part of the `x-pack`: https://www.elastic.co/guide/en/elasticsearch/reference/7.9/flattened.html
None
=> remove mapping of "app" field as "flattened" type

jobs/elasticsearch-config-lfc/templates/component-index-mappings-app.json.erb
- This was rolled back in d7fc138 due to a failure in deployment. I want to reproduce the failure since the logs have been cleaned up.
- The expected behavior is that this deploys successfully. It's a component template referenced by index templates, so there should be no conflict with existing indexes. 
- Related to https://github.com/cloud-gov/logsearch-boshrelease/issues/161
None.
=> Re-add flattened mapping for app type

src/kibana-cf_authentication/package-lock.json, src/kibana-cf_authentication/package.json
Downgrading `hapi` packages to ones that work with node 10
note: hapi/teamwork@5.0.0 seems not to work with our version of node, but I think we also can't pin it to <5.0, because hapi/catbox@11.0.0 requires hapi/teamwork@^5.1.1. I think that means this won't work, but I'm throwing it at the wall to see if it sticks. If it doesn't work, we will need to figure something else out.
- downgrade some hapi modules to satisfy requirements
None
=> chore: downgrade some hapi modules to satisfy requirements

src/kibana-cf_authentication/package-lock.json, src/kibana-cf_authentication/package.json
relies on cloud-gov/cg-deploy-logsearch#368
- downgrade hapi dependencies for node version
- mess with package-lock.json in a probably-unsafe way to convince it to install a safe version of hoek
None
=> chore: mess with dependencies even more

src/kibana-cf_authentication/package-lock.json, src/kibana-cf_authentication/package.json, src/kibana-cf_authentication/server/cache.js, src/kibana-cf_authentication/server/index.js
- roll back npm dependencies to (hopefully) working versions
This allows us to roll out new stemcells, which is a win
=> chore: roll back npm dependencies to (hopefully) working versions

jobs/elasticsearch-config-lfc/templates/component-index-mappings-app.json.erb, src/logsearch-config/src/logstash-filters/snippets/app-logmessage-app.conf
Currently, [when Logstash receives an input log that is JSON, it parses the JSON properties into a field called `app`](https://github.com/cloud-gov/logsearch-for-cloudfoundry/blob/develop/src/logsearch-config/src/logstash-filters/snippets/app-logmessage-app.conf#L24).
While this behavior is nice in that it allows logs to be searched by the custom properties from the JSON log (based on the detected field type for each JSON property), it has the problem that the first log received for an index will determine the type of any fields parsed from the JSON log.
In our case where all customer logs are ingested into a shared index per day, this is problematic, since subsequent JSON logs may have different field types for keys that existed on JSON logs that have already been ingested. When this …
=> Change parsing for JSON logs

jobs/elasticsearch-config-lfc/templates/component-index-mappings-app.json.erb, src/logsearch-config/src/logstash-filters/snippets/app-logmessage-app.conf
This reverts commit 5d706d6b4e3e6b6ed2b6b85f48e2aec384965356.
Reverts #143 because the changes aren't working in dev. They're having the same issues [described in this comment](https://github.com/cloud-gov/logsearch-boshrelease/issues/161#issuecomment-1971524540).
None, just changing how custom JSON logs are handled
=> Revert "Change parsing for JSON logs (#143)"
