templates/logsearch-jobs.yml

Increase elasticsearch data nodes to 5

---

jobs/upload-kibana-objects/spec
jobs/upload-kibana-objects/templates/bin/run
packages/logsearch-config-logstash-filters/packaging

Signed-off-by: Mike Lloyd <mike.lloyd@gsa.gov>

no more hardcoded references to be found.

---

jobs/upload-kibana-objects/spec
jobs/upload-kibana-objects/templates/bin/import-objects

fixes cloudfoundy-community/logsearch-for-cloudfoundry#331, duplicates cloudfoundy-community/logsearch-for-cloudfoundry#332 so we can roll it out sooner.

don't assume logs and login FQDNs

---

src/kibana-cf_authentication/server/uaa-provider.js

This allows us to fetch more results at a time.
It's an imperfect solution, and it would be better to implement pagination, but this should unblock us for now.
None.

get 100 results at a time

---

src/kibana-cf_authentication/server/uaa-provider.js

This should fetch all the orgs and spaces for every user every time
None

paginate orgs and spaces

---

src/kibana-cf_authentication/server/uaa-provider.js

This reverts commit a277b24f8f6621959ee58c002041a5f810e107b9.
- revert non-functional login changes 
None

Revert "paginate orgs and spaces"

---

config/blobs.yml

- correct the path for urllib3
None - just correcting a path

correct blob path

---

packages/python3/spec.lock

- actually vendor python3
None

add python3

---

config/blobs.yml
jobs/upload-kibana-objects/templates/bin/import-objects
packages/upload-kibana-objects-python3/packaging

- install venv to a subdirectory of BOSH_INSTALL_TARGET
- correct wheel names
- use copies instead of symlinks for venv
None

Make it work plz

---

jobs/elasticsearch-config-lfc/templates/index-mappings-app.json.erb
jobs/elasticsearch-config-lfc/templates/index-mappings-platform.json.erb
jobs/elasticsearch-config-lfc/templates/index-mappings.json.erb

Updating parsing rules to match cf-deployment v13 output
none

update mappings to match v13 of cf-deployment

---

src/logsearch-config/src/logstash-filters/snippets/app-logmessage-rtr.conf

pull in from 211.1.0 release to work with cf13
none

pull in from 211.1.0

---

config/blobs.yml
packages/cf-kibana/packaging
packages/cf-kibana/spec
src/kibana-cf_authentication/package.json

bump kibana

---

src/kibana-cf_authentication/public/user.js

- remove the line that kibana says to (see [here](https://www.elastic.co/guide/en/kibana/current/breaking-changes-7.6.html#_migrate_necessary_uiautoload_functionality_to_np))
None

remove the line that kibana says to

---

jobs/upload-kibana-objects/templates/bin/import-objects

- update expected landing url for kibana
None

fix upload-kibana-objects url

---

src/kibana-cf_authentication/server/helpers.js
src/kibana-cf_authentication/server/index.js
src/kibana-cf_authentication/server/routes.js

- add filtering new kibana endpoints
Fixes filtering so users can only see data they should have access to

add filtering new kibana endpoints

---

src/kibana-cf_authentication/server/helpers.js
src/kibana-cf_authentication/server/routes.js

- export the function, import the function
None

export and  import the function we need

---

jobs/elasticsearch-config-lfc/templates/index-mappings-app.json.erb
jobs/elasticsearch-config-lfc/templates/index-mappings-platform.json.erb
jobs/elasticsearch-config-lfc/templates/index-mappings.json.erb

fix erb syntax

---

jobs/elasticsearch-config-lfc/templates/component-index-mappings.json.erb

fix missing quote

---

src/kibana-cf_authentication/server/index.js
src/kibana-cf_authentication/server/routes.js

We are testing that this fix works before fixing the issue with the regex pattern matching.
- Hardcode URL for now
- None; URL change

Hardcode suggestion URL to test

---

src/kibana-cf_authentication/server/helpers.js
src/kibana-cf_authentication/server/index.js
src/kibana-cf_authentication/server/routes.js

-export and import function so it can be used
None

Filter filters

---

src/kibana-cf_authentication/server/helpers.js
src/kibana-cf_authentication/server/routes.js

- fix boolFilter type
- fix return for fallback response
None

Try to fix suggestion filter

---

src/kibana-cf_authentication/server/index.js
src/kibana-cf_authentication/server/routes.js

- Filter out apps we don't use to reduce clutter/confusion
- Filter out settings so users don't accidentally change them
This reduces the likelihood of accidents, but doesn't add any extra security.

block out endpoints we don't want to show

---

src/kibana-cf_authentication/server/routes.js

- remove stuff from the catalog(ue) so it doesn't show on the homepage
None

remove apps from catalog

---

.gitignore
packages/kibana-auth-plugin/spec
src/kibana-cf_authentication/README.md
src/kibana-cf_authentication/jest.config.js
src/kibana-cf_authentication/server/ensureKeys.test.js
src/kibana-cf_authentication/server/helpers.js

This adds some test-related stuff. Currently, the tests are only run locally because I haven't figured out a great way to test beyond that. 
- Add testing framework
- ignore testing and README files in BOSH package
- add plugin-centered README
None

Add testing

---

src/kibana-cf_authentication/server/routes.js

- allow access to management page
- restrict access to all the management tools other than saved objects
allows manipulation of saved objects

more fine-grained management capabilities

---

src/kibana-cf_authentication/server/ensureKeys.test.js

- add bad test to test ci
None

add bad test to test ci

---

src/kibana-cf_authentication/package.json
src/kibana-cf_authentication/server/filterPath.test.js
src/kibana-cf_authentication/server/helpers.js
src/kibana-cf_authentication/server/index.js

- Add server-side filtering to requests
Adds some protection against authenticated but unauthorized changes

Server side filters

---

src/kibana-cf_authentication/server/helpers.js

- Add closing curly brackets to fix tests and functions for helpers
None

Add missing closing curly bracket

---

src/kibana-cf_authentication/server/helpers.js

- declare variables to make kibana happy
None

declare variables

---

src/kibana-cf_authentication/server/filterPath.test.js
src/kibana-cf_authentication/server/helpers.js
src/kibana-cf_authentication/server/index.js

- only update url when it needs changing. updating a url seems to cause the request to restart, doing this to most/all requests then causes infinite loops.
None

only update url when it needs changing

---

src/kibana-cf_authentication/server/routes.js

- add endpoint to handle forbidden requests
None

add forbidden endpoint

---

src/kibana-cf_authentication/server/helpers.js

- correct app endpoints
- add painless_lab as denied
improves security by blocking unwanted stuff

correct app endpoints, add painless_lab as denied

---

src/kibana-cf_authentication/server/routes.js

- declare response and correct spelling
None

declare response and correct spelling

---

src/kibana-cf_authentication/server/routes.js

- set response code correctly. `response.code()` returns a new `response` rather than modifying the given `response`
None

set response code correctly

---

src/kibana-cf_authentication/server/routes.js

- add comments to point out that response objects are probably unused
None

add comments to point out that response objects are probably unused

---

src/kibana-cf_authentication/server/helpers.js

- Removed api reporting access
This turns off api reporting

Added reporting to denylist for now

---

src/kibana-cf_authentication/server/routes.js

- Changes the HTTP method from `GET` to `POST`
- None

Modify HTTP method from GET to POST

---

src/kibana-cf_authentication/server/routes.js

- Fixes handling of the `content-length` header to account for undefined values
- None

Fixes handling of the content-length header in the CSV route

---

src/kibana-cf_authentication/server/routes.js

- Corrects `jobsParams` to `jobParams`
- None

Fixes the jobParam parameter name

---

src/kibana-cf_authentication/server/routes.js

Fixes URL being used to override CSV generation

---

src/kibana-cf_authentication/server/routes.js

- Adjust Rison decoding
- None

Attempt to fix payload decoding for Rison

---

src/kibana-cf_authentication/server/helpers.js
src/kibana-cf_authentication/server/routes.js

- Shift Rison decoding/encoding back into the helper
- Try to explicitly account for the `jobParams` key
- None

Another attempt at fixing the JSON/Rison parsing

---

src/kibana-cf_authentication/server/helpers.js
src/kibana-cf_authentication/server/routes.js

- Uses a temporary variable for JSON parsing
- Adds logging statements to see information
- Logging statements need to be removed once debugging is complete; there's a `TODO` note in the code for this

Add debugging lines to figure out issue with Rison decoding

---

src/kibana-cf_authentication/server/helpers.js

This changeset fixes the debugging log statements so that they will actually appear in the logs, which can be found using this method: https://stackoverflow.com/a/17790708
- Swap console.log statements to server.log statements
- Log statements will need to be removed once debugging is complete

Fix debugging log statements

---

src/kibana-cf_authentication/server/routes.js

This changeset fixes two issues with the filter CSV route handling.
- Adjusts the cached user account info to match the search URL handlers just in case
- Adds the `filterCSVReportingQuery` to the `helpers` module import
- Debugging log statements will need to be removed when finished

Fix two issues with the filter CSV route handling

---

src/kibana-cf_authentication/server/helpers.js
src/kibana-cf_authentication/server/routes.js

- Adds missing export for `filterCSVReportingQuery`
- Removes extraneous `rison-node` import
- Remove logging statements when debugging is complete

Adjust module exports and remove extra module import

---

src/kibana-cf_authentication/server/helpers.js

- Adjusts logging statements to verify filter adjustments for CSV reporting
- The logging statements must be removed when debugging is finished

Add logging statements to verify filter changes work

---

packages/python3/spec.lock

- Updated cg-python3 release with bionic packing fix
Updated cg-python3 release with bionic packaging fix

adding in new cut of cg-python3-bosh-release with bionic package fix

---

jobs/upload-kibana-objects/spec
packages/logsearch-config-logstash-filters/packaging
packages/logsearch-config-logstash-filters/spec
packages/ruby-2.4.6-r0.16.0/spec.lock
packages/ruby-3.1/spec.lock

Ruby version bump

---

jobs/upload-kibana-objects/templates/bin/run

- Missed a spot for ruby
-
-
None

missed a spot for ruby

---

jobs/elasticsearch-config-lfc/templates/component-index-mappings-app.json.erb

This reverts commit e3d834e5c6fc531871afb53e80fa26f664d9fa61, reversing changes made to 4d7a00d5d74294607e18110e2ed9c833347d923e.
See https://github.com/cloud-gov/logsearch-boshrelease/issues/161#issuecomment-1971524540 for full details.
None.

Revert "Merge pull request #119 from cloud-gov/flattened"

---

jobs/upload-kibana-objects/templates/kibana-objects/dashboard/App-Metrics-by-instance.erb
jobs/upload-kibana-objects/templates/kibana-objects/visualization/App-METRIC-CPU-usage-by-instance.json.erb
jobs/upload-kibana-objects/templates/kibana-objects/visualization/App-METRIC-disk-usage-by-instance.json.erb
jobs/upload-kibana-objects/templates/kibana-objects/visualization/App-METRIC-memory-usage-by-instance.json.erb

- Add dashboard showing application metrics by instance
None

Add metrics dashboard by instance

---

src/kibana-cf_authentication/server/cache.js
src/kibana-cf_authentication/server/catbox-redis/index.js
src/kibana-cf_authentication/server/index.js

- correct references to packages that moved under the @hapi namespace
-
-
None

fix: correct references to packages that moved under the @hapi namespace

---

src/kibana-cf_authentication/package-lock.json
src/kibana-cf_authentication/package.json

- revert npm engine version change (it broke CI and wasn't necessary)
None

fix: revert npm engine version

---

src/kibana-cf_authentication/package-lock.json
src/kibana-cf_authentication/package.json

-  pin transitive dependency because npm cant figure it out itself
None

chore: pin transitive dependency because npm cant figure it out itself

---

src/kibana-cf_authentication/package-lock.json

- update dependencies for Kibana auth plugin
-
-
Updating dependencies to patched versions

update dependencies for Kibana auth plugin
